version: "3.3"
services:
  # prometheus:
  #   build: './prometheus'
  #   restart: always
  #   container_name: prometheus
  #   privileged: true
  #   ports:
  #     - '9090:9090'
  #   volumes:
  #     - "${MASTER}/data:/var/lib/mysql"
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    privileged: true
    ports:
      - '9090:9090'
    volumes:
      - "${PROMETHEUS_IDR}/prometheus:/etc/prometheus/"
  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    ports:
      - 3000:3000
    user: "104"