version: "3.3"
services:
  nginx:
    restart: always
    image: nginx:1.18.0
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_DIR}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DIR}/log:/var/log/nginx
      # - ${NGINX_DIR}/www:/var/www
